#salesforce
salesforce:
  username: "seshuchennupati1@gmail.com"
  passcode: "Seshu@2027"
  token: "HAqYFPRzXjPczO0kUKbmrJ0u"
  
  
# listener configuration details 
https:
  listener:
   host: "0.0.0.0"
   port: "8081"
 
# TLS key store configuration details     
key-store:   
   path: "server-keystore.jks"
   password: "mule123"
   keyPassword: "mule123"
   
# TLS trusted   
trust-store:   
   path: "client-truststore.jks"
   password: "mule123"